const router = require('express').Router();
const controller = require('../controllers/clienteController');
const prospeccao = require('../controllers/prospeccaoController');
const importacao = require('../controllers/importacaoController');
const express = require('express');
const csvBody = express.raw({ type: 'text/csv', limit: '1mb' });
const excelBody = express.raw({ type: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel.sheet.macroenabled.12'], limit: '5mb' });
router.post('/importacao/previa', csvBody, excelBody, importacao.previa);
router.post('/importacao', csvBody, excelBody, importacao.importar);
router.get('/', controller.listar);
router.get('/:id', controller.buscar);
router.post('/', controller.salvar);
router.post('/:id/contato', prospeccao.registrar);
router.get('/:id/prospeccoes', prospeccao.listar);
router.put('/:id/prospeccoes/:contatoId', prospeccao.resultado);
router.post('/:id/nao-contatar', prospeccao.naoContatar);
router.put('/:id/followup', controller.followup);
router.put('/:id', controller.salvar);
router.delete('/:id', controller.excluir);
module.exports = router;
