const {test}=require('node:test'),assert=require('node:assert/strict');
const v=require('../services/configuracaoValidation'),model=require('../models/configuracaoModel');
const gerar=require('../../frontend/geradorMensagens').gerar;
test('Configurações: padrões atuais e cópias independentes',()=>{const a=v.valores();assert.equal(a.nome_remetente,'Pedro Henrique');assert.equal(a.profissao_remetente,'desenvolvedor web');assert.equal(a.leads_por_pagina,25);assert.equal(a.tela_inicial,'dashboard');a.nome_remetente='x';assert.equal(v.valores().nome_remetente,'Pedro Henrique')});
for(const k of ['nome_remetente','profissao_remetente'])test('Configurações: valida '+k,()=>{for(const valor of ['',null,'a'.repeat(101),'<b>Texto</b>'])assert.ok(v.validar({...v.valores(),[k]:valor}).erros[k]);assert.equal(v.validar({...v.valores(),[k]:'  Maria   Silva  '}).dados[k],'Maria Silva')});
for(const n of ['academia','clinica','estetica'])test('Configurações: demo '+n+' exige URL segura quando habilitada',()=>{const f='demo_'+n+'_disponivel',u='demo_'+n+'_url';for(const url of ['', 'javascript:alert(1)','data:text/html,oi','ftp://example.com','https://user:pass@example.com','https://'])assert.ok(v.validar({...v.valores(),[f]:true,[u]:url}).erros[u]);for(const url of ['https://example.com/demo','http://localhost:3000/demo'])assert.deepEqual(v.validar({...v.valores(),[f]:true,[u]:url}).erros,{});assert.deepEqual(v.validar(v.valores()).erros,{})});
for(const n of [25,50,100])test('Configurações: paginação '+n,()=>assert.deepEqual(v.validar({...v.valores(),leads_por_pagina:n}).erros,{}));
test('Configurações: rejeita preferências inválidas e campos técnicos',()=>{for(const o of [{leads_por_pagina:10},{leads_por_pagina:'25'},{tela_inicial:'dados'},{DB_PASSWORD:'x'},{demo_academia_disponivel:'sim'}])assert.ok(Object.keys(v.validar({...v.valores(),...o}).erros).length);for(const tela_inicial of ['dashboard','lista','pipeline'])assert.deepEqual(v.validar({...v.valores(),tela_inicial}).erros,{})});
test('Configurações: tabela vazia usa padrões e SQL é parametrizado',async()=>{assert.deepEqual(await model.obter({execute:async()=>[[]]}),v.valores());let sql,params;const data={...v.valores(),nome_remetente:"D'Ávila"};await model.salvar(data,{execute:async(s,p)=>{sql=s;params=p}});assert.ok(!sql.includes(data.nome_remetente));assert.ok(params.includes(data.nome_remetente));});
for(const estrategia of ['curiosidade','oportunidade','problema_sutil','visualizacao','demonstracao','pergunta','autoridade','direta'])test('Configurações no gerador: '+estrategia+' preserva variante e aceita perfil',()=>{const c={...v.valores(),nome_remetente:'Marina',profissao_remetente:'designer',demo_academia_disponivel:true,demo_academia_url:'https://example.com/demo'};const r=gerar({nome_empresa:'Academia A',nicho:'Academia'},estrategia,{configuracao:c});assert.match(r.texto,/Marina/);assert.match(r.texto,/designer/);assert.equal(r.variant_id,estrategia+'_01');assert.doesNotMatch(r.texto,/https?:|Pedro Henrique|undefined|null/)});
test('Configurações: demo automática respeita habilitação e nicho',()=>{let anterior;const c={...v.valores(),demo_academia_disponivel:true,demo_academia_url:'https://example.com'};const usadas=new Set();for(let i=0;i<8;i++){anterior=gerar({nicho:'Academia'},'automatica',{anterior,random:()=>0,configuracao:c});usadas.add(anterior.estrategia)}assert.equal(usadas.size,8);assert.throws(()=>gerar({nicho:'Clínica'},'demonstracao',{configuracao:c}),/Nenhuma/);assert.throws(()=>gerar({nicho:'Academia'},'demonstracao',{configuracao:v.valores()}),/Nenhuma/)});
test('Configurações HTTP: obter, salvar, erros e restaurar padrões',async()=>{const orig={...model},app=require('../server');let state=v.valores();model.obter=async()=>state;model.salvar=async d=>(state=d);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port+'/api/configuracoes',put=d=>fetch(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});try{assert.deepEqual(await (await fetch(url)).json(),v.valores());const data={...state,nome_remetente:'  Marina  ',leads_por_pagina:100,tela_inicial:'lista'};assert.equal((await put(data)).status,200);assert.equal((await (await fetch(url)).json()).nome_remetente,'Marina');assert.equal((await put({...data,nome_remetente:''})).status,400);assert.equal((await put(v.valores())).status,200);assert.deepEqual(state,v.valores());model.salvar=async()=>{throw Error('senha')};const r=await put(v.valores());assert.equal(r.status,500);assert.ok(!(await r.text()).includes('senha'));}finally{Object.assign(model,orig);server.closeAllConnections();await new Promise(r=>server.close(r));}});

test('Datas: apresentação brasileira sem alterar a string de armazenamento',()=>{const {formatar}=require('../../frontend/datas');const original='2026-09-28 15:30:00';assert.equal(formatar(original),'28/09/2026 15:30:00');assert.equal(original,'2026-09-28 15:30:00');assert.equal(formatar('2026-09'),'09/2026');assert.equal(formatar(null),null)});

test('Configurações: copy padrão idêntica nas oito mensagens',()=>{const templates=require('../../frontend/mensagemTemplates'),lead={nome_empresa:'Academia Alpha',nicho:'Academia',instagram:'@alpha',possui_site:0},antes=templates.demos.academia.demoDisponivel;try{templates.demos.academia.demoDisponivel=true;const c={...v.valores(),demo_academia_disponivel:true,demo_academia_url:'https://example.com'};for(const estrategia of Object.keys(templates.mensagens))assert.equal(gerar(lead,estrategia).texto,gerar(lead,estrategia,{configuracao:c}).texto);}finally{templates.demos.academia.demoDisponivel=antes;}});
for(const [grupo,nicho] of [['academia','Academia'],['clinica','Clínica'],['estetica','Estética']])test('Demo configurada no gerador para '+grupo,()=>{const c={...v.valores(),['demo_'+grupo+'_disponivel']:true,['demo_'+grupo+'_url']:'https://example.com/demo'};assert.match(gerar({nicho},'demonstracao',{configuracao:c}).texto,/Tenho uma proposta/);});
