const {test}=require('node:test');const assert=require('node:assert/strict');const {criarDashboard}=require('../../frontend/dashboard');
function tela(){
 const nodes=new Map();function node(){return {value:'',textContent:'',children:[],listeners:{},replaceChildren(...c){this.children=c},append(...c){this.children.push(...c)},setAttribute(){},addEventListener(k,fn){this.listeners[k]=fn}}}const get=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)};
 const zero={numerador:0,denominador:0,percentual:0},state={calls:[],opened:[],fail:false},data={resumo:{leads:0,contatados:0,contatos:0,responderam:0,interessados:0,negociacao:0,fechados:0},taxas:{resposta:zero,interesse:zero,fechamento:zero},funil:[],pipeline:[],followups:{hoje:0,atrasados:0,proximos:0},estrategias:[{nome:'Curiosidade',contatados:0,responderam:0,interessados:0,fechados:0,taxa_resposta:zero,amostra_pequena:true}],variantes:[],nichos:[],estados:[],evolucao:[],periodo:{agrupamento:'mes'},opcoes:[]};
 get('dashboard-periodo').value='todo';const api=criarDashboard({document:{getElementById:get,createElement:node},localidades:{estados:[{uf:'MA',nome:'Maranhão'}],cidades:uf=>uf?[{nome:'São Luís'}]:[]},abrirLista:(...v)=>state.opened.push(v),fetch:async url=>{state.calls.push(url);if(state.fail)throw Error('offline');return {ok:true,json:async()=>data}}});return {get,state,data,api};
}
const texto=n=>n.textContent+n.children.map(texto).join(' ');
test('Dashboard frontend: vazio, taxas absolutas, amostra e retorno à lista',async()=>{const t=tela();await t.api.carregar();assert.match(texto(t.get('dashboard-taxas')),/0%/);assert.match(texto(t.get('dashboard-estrategias')),/Amostra pequena/);assert.match(t.get('dashboard-aviso').textContent,/Sem dados/);t.get('dashboard-followups').children[1].listeners.click();assert.equal(t.state.opened[0][0],'atrasados');});
test('Dashboard frontend: filtros combinados, datas e troca de UF limpa cidade',async()=>{const t=tela();t.get('dashboard-estado').value='MA';t.get('dashboard-estado').listeners.change();t.get('dashboard-cidade').value='São Luís';t.get('dashboard-nicho').value='Clínica';t.get('dashboard-periodo').value='personalizado';t.get('dashboard-periodo').listeners.change();assert.equal(t.get('dashboard-inicio').required,true);t.get('dashboard-inicio').value='2026-09-01';t.get('dashboard-fim').value='2026-09-28';let prevenido=false;await t.get('dashboard-filtros').listeners.submit({preventDefault(){prevenido=true}});assert.equal(prevenido,true);const q=new URL('http://localhost'+t.state.calls[0]).searchParams;assert.equal(q.get('cidade'),'São Luís');assert.equal(q.get('nicho'),'Clínica');assert.equal(q.get('inicio'),'2026-09-01');t.get('dashboard-estado').value='';t.get('dashboard-estado').listeners.change();assert.equal(t.get('dashboard-cidade').value,'');assert.equal(t.get('dashboard-cidade').disabled,true)});
test('Dashboard frontend: erro mantém dados anteriores e texto não vira HTML',async()=>{const t=tela();t.data.estrategias[0].nome='<script>alert(1)</script>';await t.api.carregar();assert.match(texto(t.get('dashboard-estrategias')),/<script>/);const cards=t.get('dashboard-cards').children;t.state.fail=true;await t.api.carregar();assert.equal(t.get('dashboard-cards').children,cards);assert.match(t.get('dashboard-aviso').textContent,/desatualizados/)});
