const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {criarTema}=require('../../frontend/tema'),{criarNavegacao}=require('../../frontend/navegacao'),ui=require('../../frontend/interface');
function doc(){const nodes=new Map();const el=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v},getAttribute(k){return this.attrs[k]},addEventListener(k,v){this.listeners[k]=v},focus(){this.focused=true}});return nodes.get(id)};return {getElementById:el,documentElement:el('root'),listeners:{},addEventListener(k,v){this.listeners[k]=v}};}
for(const dark of [false,true])test('Tema: fallback '+(dark?'escuro':'claro'),()=>{const d=doc();criarTema({document:d,storage:{getItem:()=>null},media:{matches:dark,addEventListener(){}}});assert.equal(d.documentElement.attrs['data-theme'],dark?'dark':'light');});
test('Tema: escolha persistida prevalece e alterna com nome acessível',()=>{const d=doc(),cache={'lead-crm-tema':'light'},storage={getItem:k=>cache[k],setItem:(k,v)=>cache[k]=v};const tema=criarTema({document:d,storage,media:{matches:true,addEventListener(){}}});tema.alternar();assert.equal(cache['lead-crm-tema'],'dark');assert.equal(d.getElementById('alternar-tema').attrs['aria-label'],'Ativar modo claro');criarTema({document:d,storage,media:{matches:false,addEventListener(){}}});assert.equal(d.documentElement.attrs['data-theme'],'dark');});
test('Tema: armazenamento indisponível e preferência do sistema não causam erro',()=>{const d=doc();let change;const t=criarTema({document:d,storage:{getItem(){throw Error()},setItem(){throw Error()}},media:{matches:false,addEventListener(k,fn){change=fn}}});change({matches:true});assert.equal(d.documentElement.attrs['data-theme'],'dark');t.alternar();change({matches:true});assert.equal(d.documentElement.attrs['data-theme'],'light');});
test('Navegação: cinco áreas, seção ativa e menu mobile por teclado',()=>{const d=doc(),calls=[];const n=criarNavegacao({document:d,aoDashboard:()=>calls.push('dashboard'),aoVisao:v=>calls.push(v)});for(const a of ['dashboard','lista','pipeline','dados','configuracoes']){n.navegar(a);assert.equal(d.getElementById('nav-'+a).attrs['aria-current'],'page');assert.equal(d.getElementById('area-clientes').hidden,!['lista','pipeline'].includes(a));}d.getElementById('menu-mobile').listeners.click();assert.equal(d.getElementById('menu-mobile').attrs['aria-expanded'],'true');d.listeners.keydown({key:'Escape'});assert.equal(d.getElementById('menu-mobile').attrs['aria-expanded'],'false');assert.equal(d.getElementById('menu-mobile').focused,true);assert.deepEqual(calls,['dashboard','lista','pipeline']);});
test('Vazio: distingue base sem leads de busca sem resultados',()=>{assert.match(ui.estadoVazio(0,false),/Novo lead/);assert.match(ui.estadoVazio(0,true),/filtros/);assert.equal(ui.estadoVazio(1,true),'')});
test('Formulários: IDs únicos, descrições existentes e controles essenciais preservados',()=>{const html=fs.readFileSync(path.resolve(__dirname,'../../frontend/index.html'),'utf8'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const [,names] of html.matchAll(/aria-(?:describedby|labelledby|controls)="([^"]+)"/g))for(const n of names.split(' '))assert.ok(ids.includes(n),n);for(const id of ['cadastro-dialog','detalhes','config-form','csv-arquivo','backup-confirmacao','menu-mobile','alternar-tema'])assert.ok(ids.includes(id));assert.match(html,/prefers|tema.js/);assert.ok(!html.includes('https://cdn.'));});
test('Feedback de formulário: usa texto e aria-invalid por campo',()=>{const d=doc(),input={name:'nome_empresa',setAttribute(k,v){this[k]=v}};d.getElementById('formulario').querySelectorAll=()=>[input];ui.errosFormulario(d,{nome_empresa:'Informe a empresa.'});assert.equal(input['aria-invalid'],'true');assert.equal(d.getElementById('erro-lead-nome_empresa').textContent,'Informe a empresa.');ui.errosFormulario(d);assert.equal(input['aria-invalid'],'false');});
